---
title: "07_preliminary-analyses"
author: "Anjum K. Gujral"
date: '2024-11-11'
output:
  html_document:
    df_print: paged
  pdf_document:
    output_dir: /Users/anjumgujral/Documents/repos/yuba-phys
---
#load packages
```{r, echo = FALSE, message = FALSE, warning = FALSE}
library('tinytex')
library('dplyr')
library('tidyverse')
library('ggplot2')
library('emmeans')
library('lme4')
library('lmerTest')
library('gridExtra')
library('ggcorrplot')
library('corrplot')
library('ggpubr')
library('emmeans')
```

# load data
```{r}
trait_data1<- read.csv("/Users/anjumgujral/Box Sync/yuba-phys_data/traits/yuba-phys-prepped-field-data-2024_2025.csv")

# subset data frame by species 
ABCO <- trait_data1[trait_data1$species == 'ABCO',]
PILA <- trait_data1[trait_data1$species == 'PILA',]
PIPO <- trait_data1[trait_data1$species == 'PIPO',]
ABMA <- trait_data1[trait_data1$species == 'ABMA',]

```

#size distribution
```{r, echo = FALSE, message = FALSE, warning = FALSE}

ggplot(trait_data1, aes(x = diameter_complete, fill = size)) +
  geom_histogram(binwidth = 0.5, position = "dodge", alpha = 0.7, color = "black") +
  labs( 
       x = "Basal diameter (cm)", 
       y = "Frequency") +
  scale_fill_manual(values = c("lightblue", "lightgreen")) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank())

```

# site distributions
```{r, echo = FALSE, message = FALSE, warning = FALSE}


ggplot(trait_data1, aes(x = diameter_complete, y = canopy_closure, color = species)) +
  geom_point(size = 3, alpha = 0.7) +
  labs(
       y = "Canopy closure", 
       x = "Basal diameter (cm)") +
  scale_color_manual(values = c("blue", "green", "red", "purple")) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank())

# is canopy closure equal distributed across elevation bands?
ggplot(trait_data1, aes(x = elevation, y = canopy_closure, fill = microsite)) +
  geom_boxplot() +
  labs(
    x = "Elevation",
    y = "Canopy Closure"
  ) +
    theme_bw() +
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank())+
  scale_fill_manual(values = c("skyblue", "lightgreen", "purple"))

# create a new variable combining size_class and elevation
trait_data1$size_elevation <- interaction(trait_data1$size, trait_data1$elevation)

# are seedlings and saplings of each species equally distributed across canopy closure?
ggplot(trait_data1, aes(x = species, y = canopy_closure)) +
  geom_boxplot(alpha = 0.5, outlier.size = 3, outlier.colour = "black") +
  geom_point(aes(color = size_elevation), 
             position = position_jitter(width = 0.2, height = 0), 
             alpha = 0.7, size = 3) +
  labs(
    y = "Canopy closure", 
    x = "Species",
    color = "Size & Elevation"  
  ) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank()
  )


ggplot(trait_data1, aes(x = microsite, y = canopy_closure)) +
  geom_boxplot(alpha = 0.5, outlier.size = 3, outlier.colour = "black") +
  geom_point(aes(color = size_elevation), 
             position = position_jitter(width = 0.2, height = 0), 
             alpha = 0.7, size = 3) +
  labs(
    y = "Canopy closure", 
    x = "Microsite level", 
    color = "Size & Elevation"  
  ) +
  facet_wrap(~ species, scales = "free_y") +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank()
  )


# how similar is stand density between plots at high and low elevation
ggplot(trait_data1, aes(x = elevation, y = stand_basal_area, fill = elevation)) +
  geom_boxplot() +
  labs(
    x = "Elevation",
    y = "Stand Basal Area"
  ) +
    theme_bw() +
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank())+
  scale_fill_manual(values = c("skyblue", "lightgreen", "purple"))



ggplot(trait_data1, aes(x = species, y = stand_basal_area)) +
  geom_boxplot(alpha = 0.5, outlier.size = 3, outlier.colour = "black") +
  geom_point(aes(color = size_elevation), 
             position = position_jitter(width = 0.2, height = 0), 
             alpha = 0.7, size = 3) +
  labs(
    y = "Stand Basal Area ", 
    x = "Species",
    color = "Size & Elevation"
  ) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank()
  )


ggplot(trait_data1, aes(x = microsite, y = stand_basal_area)) +
  geom_boxplot(alpha = 0.5, outlier.size = 3, outlier.colour = "black") +
  geom_point(aes(color = size_elevation), 
             position = position_jitter(width = 0.2, height = 0), 
             alpha = 0.7, size = 3) +
  labs(
    y = "Stand Basal Area", 
    x = "Microsite level", 
    color = "Size & Elevation" 
  ) +
  facet_wrap(~ species, scales = "free_y") +
  
  theme_bw() +
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank()
  )

```

# environmental variables
```{r}
# Create a correlation matrix for environmental variables
cor_matrix <- cor(trait_data1[, c("canopy_closure", "elevation_ft", "stand_basal_area")], use = "pairwise.complete.obs")
print(cor_matrix)

cor(trait_data1$elevation_ft, trait_data1$stand_basal_area, 
    use = "complete.obs", method = "pearson")

cor.test(trait_data1$stand_basal_area, trait_data1$elevation_ft, method="pearson")

# Create a custom set of axis labels (modify as per your needs)
custom_labels <- c("Canopy Closure", "Elevation (ft)", "Stand Basal Area")

colnames(cor_matrix) <- custom_labels
rownames(cor_matrix) <- custom_labels

# Visualize the correlation matrix with custom axis labels
corrplot(cor_matrix, 
         method = "color",          
         type = "lower",            
         order = "hclust",          
         addCoef.col = "black",    
         tl.col = "black",          
         tl.srt = 45,               
         tl.labels = custom_labels, 
         title = "Correlation Plot"
)

# There is a statistically significant difference between 2024 and 2025 predawn and midday water potential means. On average, predawn WP is higher (more negative) in 2024 and midday is 
t.test(predawn_MPa_combined ~ year, data = trait_data1, paired = FALSE)

t.test(predawn_MPa_combined ~ year, 
       data = trait_data1, 
       paired = FALSE,
       subset = year %in% c("2024", "2025"))

```

# table S1 models
```{r}
# run this model for all species 'ABCO', 'ABMA', 'PILA', 'PIPO' for results in table S1
# run this model for the following response variables 'midday_MPa_combined', 'P50_combined', '

mod1 <- lmer(P50_combined ~ diameter_complete_scaled + canopy_closure_scaled + elevation_ft_scaled + (1|plot) + (1|year), data = ABCO)
summary(mod1)

```

# table S2 models
```{r}
# run this model for all species 'ABCO', 'ABMA', 'PILA', 'PIPO' for results in table S2
# run this model for the following response variables 'P50_combined', 'HSM_

mod2 <- lmer(P50_combined ~diameter_complete_scaled * predawn_scaled * canopy_closure_scaled + elevation_ft_scaled + (1|plot) + (1|year), data = ABCO)
summary(mod2)

```

# table S3 models
```{r}
mod3 <- lmer(internode_length_1_2~ diameter_complete_scaled + predawn_scaled + HSM_midday_P50_mean_scaled + canopy_closure_scaled + elevation_ft_scaled + (1|plot), data = ABCO)
summary(mod3)

# Fit linear model of growth on diameter
growth_diam_mod <- lm(internode_length_1_2 ~ diameter_complete, data = trait_data1, na.action = na.exclude)

# Extract residuals and add as new column
trait_data1$growth_residuals <- residuals(growth_diam_mod)

ggplot(trait_data1, aes(x = log(diameter_complete), y = log(internode_length_1_2), color = species)) +
  geom_point(size = 3, alpha = 1) +  
  geom_smooth(method = "lm", se = TRUE, alpha = 0.3) +  
  labs(x = "log Diameter at root collar (cm)", y = "log Internode length (cm)") +
  theme_bw() +
  scale_color_manual(values = c(
    "ABCO" = "mediumturquoise",
    "PIPO" = "lawngreen",
    "ABMA" = "maroon3",
    "PILA" = "lightslateblue"
  )) +
  #scale_y_reverse()  +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "none"
  )

```

# table S4-5 models
```{r}
mod4 <- lmer(HSM_midday_P50_mean ~ species * diameter_complete_scaled * elevation_ft_scaled * canopy_closure_scaled + (1|plot) + (1|year), data = trait_data1)
summary(mod4)

# table 4-5 pairwise comparisons using emmeans
emms1 <- emmeans(mod4, pairwise ~ species)
summary(emms1$emmeans)
summary(emms1$contrasts) #automatically adjusts to tukey, for multiple comparisons

```

